name: Astronomer CI - Deploy code

on:
  push:
    branches:
      - main

vars:
  ASTRO_EXAMPLE_DEPLOYMENT_ID: your_deployment_id_here

env:
  ## Set API Token as an environment variable
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.10.1
      with:
        deployment-id: ${{ vars.ASTRO_EXAMPLE_DEPLOYMENT_ID }}
        parse: true
        description: ${{ github.event.head_commit.message }} - https://github.com/${{ github.repository }}/commit/${{ github.sha }}